version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10

jobs:
  release_dry:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - dependency-cache-{{ .Branch }}-
      - run: npm ci
      - run: npx semantic-release --dry-run
      - save_cache:
          paths:
            - ~/.npm
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - dependency-cache-{{ .Branch }}-
      - run: npm ci
      - run: npx semantic-release -d --no-ci

workflows:
  version: 2
  test_and_release:
    jobs:
      - release_dry:
          filters:
            branches:
              only: /^release.*/
      - release:
          filters:
            branches:
              only: /^release.*/
