version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:10

jobs:
  release:
    <<: *defaults
    steps:
      - checkout
      - run: npx semantic-release --no-ci

workflows:
  version: 2
  test_and_release:
    jobs:
      - release:
          filters:
            branches:
              only: master
