version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10

jobs:
  release_dry:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npx semantic-release --dry-run
  release:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: semantic-release
          command: |
            if git log --format=%B -n 1 | grep -E '.*\[skip semantic-release\].*' >/dev/null; then
              echo "[skip semantic-release]を含むのでskipします。"
            else
              echo "[skip semantic-release]を含まないのでsemantic-releaseを実行します。"
              npm i
              npx semantic-release --debug
            fi

workflows:
  version: 2
  test_and_release:
    jobs:
      - release_dry:
          filters:
            branches:
              only: /^release\/M.*/
      - release:
          filters:
            branches:
              only: /^release\/M.*/
