name: action github release qadoc

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

jobs:
  release-qadoc:
    name: runner / github-release-qadoc
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: github-release-qadoc
        uses: locona/action-github-release-qadoc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ secrets.GITHUB_REPOSITORY }}
          issue: 55
