name: action github release qadoc

on:
  push:
    branches:
      - master

jobs:
  release-qadoc:
    name: runner / github-release-qadoc
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: github-release-qadoc
        uses: locona/action-github-release-qadoc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ env.GITHUB_REPOSITORY }}
          issue: 55
